project:
  type: book
  output-dir: docs

book:
  title: "Model-Book"
  downloads: [pdf, docx]
  crossref:
    chapters: false
  author:
    - name: Jane Doe
  chapters:
    - index.qmd
    - people.qmd
    - projects.qmd
    - references.qmd

  site-url: https://sefsc-caribbean-strategic-planning.github.io/Model-Book/
  repo-url: https://github.com/SEFSC-Caribbean-Strategic-Planning/Model-Book
  repo-actions: [edit, source, issue]
  search: true

bibliography: references.bib

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    toc-depth: 2

editor: visual

